name: Access To Crypto Currency Wallets By Uncommon Applications
id: f41b0311-44f9-44f0-816d-dd45e39d4bc8
author: X__Junior (Nextron Systems)
date: 2024-07-29
severity: medium
description: 'Detects file access requests to crypto currency files by uncommon processes.

  Could indicate potential attempt of crypto currency wallet stealing.

  '
status: experimental
modified: ''
logsource:
  category: file_access
  product: windows
tactics:
- Credential-access
relevantTechniques:
- T1003
query: 'DeviceFileEvents

  | where ((FileName contains "\\AppData\\Roaming\\Ethereum\\keystore\\" or FileName
  contains "\\AppData\\Roaming\\EthereumClassic\\keystore\\" or FileName contains
  "\\AppData\\Roaming\\monero\\wallets\\") or (FileName endswith "\\AppData\\Roaming\\Bitcoin\\wallet.dat"
  or FileName endswith "\\AppData\\Roaming\\BitcoinABC\\wallet.dat" or FileName endswith
  "\\AppData\\Roaming\\BitcoinSV\\wallet.dat" or FileName endswith "\\AppData\\Roaming\\DashCore\\wallet.dat"
  or FileName endswith "\\AppData\\Roaming\\DogeCoin\\wallet.dat" or FileName endswith
  "\\AppData\\Roaming\\Litecoin\\wallet.dat" or FileName endswith "\\AppData\\Roaming\\Ripple\\wallet.dat"
  or FileName endswith "\\AppData\\Roaming\\Zcash\\wallet.dat")) and (not(((InitiatingProcessFolderPath
  startswith "C:\\Program Files (x86)\\" or InitiatingProcessFolderPath startswith
  "C:\\Program Files\\" or InitiatingProcessFolderPath startswith "C:\\Windows\\system32\\"
  or InitiatingProcessFolderPath startswith "C:\\Windows\\SysWOW64\\") or InitiatingProcessFolderPath
  =~ "System"))) and (not(((InitiatingProcessFolderPath endswith "\\MpCopyAccelerator.exe"
  or InitiatingProcessFolderPath endswith "\\MsMpEng.exe") and InitiatingProcessFolderPath
  startswith "C:\\ProgramData\\Microsoft\\Windows Defender\\")))'
eventGroupingSettings:
  aggregationKind: SingleAlert
queryFrequency: P1D
queryPeriod: P1D
enabled: true
entityMappings: null
sentinelEntitiesMappings: null
triggerThreshold: 0
suppressionDuration: PT5H
suppressionEnabled: false
triggerOperator: GreaterThan
kind: Scheduled
