name: Access To Windows Credential History File By Uncommon Applications
id: 7a2a22ea-a203-4cd3-9abf-20eb1c5c6cd2
author: Nasreddine Bencherchali (Nextron Systems)
date: 2022/10/17
severity: medium
description: 'Detects file access requests to the Windows Credential History File
  by an uncommon application.

  This can be a sign of credential stealing. Example case would be usage of mimikatz
  "dpapi::credhist" function

  '
status: experimental
modified: 2024/07/29
logsource:
  category: file_access
  product: windows
tactics:
- Credential Access
relevantTechniques:
- T1555
query: 'DeviceFileEvents

  | where FileName endswith "\\Microsoft\\Protect\\CREDHIST" and (not((InitiatingProcessFolderPath
  =~ "C:\\Windows\\explorer.exe" or (InitiatingProcessFolderPath startswith "C:\\Program
  Files\\" or InitiatingProcessFolderPath startswith "C:\\Program Files (x86)\\" or
  InitiatingProcessFolderPath startswith "C:\\Windows\\system32\\" or InitiatingProcessFolderPath
  startswith "C:\\Windows\\SysWOW64\\"))))'
eventGroupingSettings:
  aggregationKind: SingleAlert
queryFrequency: P1D
queryPeriod: P1D
enabled: true
entityMappings: null
sentinelEntitiesMappings: null
triggerThreshold: 0
suppressionDuration: PT5H
suppressionEnabled: false
triggerOperator: GreaterThan
kind: Scheduled
