name: Access To Windows Outlook Mail Files By Uncommon Application
id: fc3e237f-2fef-406c-b90d-b3ae7e02fa8f
author: frack113
date: 2024/05/10
severity: low
description: 'Detects file access requests to Windows Outlook Mail by uncommon processes.

  Could indicate potential attempt of credential stealing.

  Requires heavy baselining before usage

  '
status: experimental
modified: ''
logsource:
  category: file_access
  product: windows
tactics:
- Defense Evasion
relevantTechniques:
- T1070
query: 'DeviceFileEvents

  | where (FileName contains "\\AppData\\Local\\Comms\\Unistore\\data" or FileName
  endswith "\\AppData\\Local\\Comms\\UnistoreDB\\store.vol") and (not(((InitiatingProcessFolderPath
  contains ":\\Program Files (x86)\\" or InitiatingProcessFolderPath contains ":\\Program
  Files\\" or InitiatingProcessFolderPath contains ":\\Windows\\system32\\" or InitiatingProcessFolderPath
  contains ":\\Windows\\SysWOW64\\") or InitiatingProcessFolderPath =~ "System")))
  and (not(((InitiatingProcessFolderPath contains ":\\ProgramData\\Microsoft\\Windows
  Defender\\" and (InitiatingProcessFolderPath endswith "\\MpCopyAccelerator.exe"
  or InitiatingProcessFolderPath endswith "\\MsMpEng.exe")) or (InitiatingProcessFolderPath
  endswith "\\thor64.exe" or InitiatingProcessFolderPath endswith "\\thor.exe"))))'
eventGroupingSettings:
  aggregationKind: SingleAlert
queryFrequency: P1D
queryPeriod: P1D
enabled: true
entityMappings: null
sentinelEntitiesMappings: null
triggerThreshold: 0
suppressionDuration: PT5H
suppressionEnabled: false
triggerOperator: GreaterThan
kind: Scheduled
