name: Access To Browser Credential Files By Uncommon Application
id: 91cb43db-302a-47e3-b3c8-7ede481e27bf
author: frack113
date: 2022/04/09
severity: medium
description: 'Detects file access requests to browser credential stores by uncommon
  processes.

  Could indicate potential attempt of credential stealing.

  Requires heavy baselining before usage

  '
status: experimental
modified: 2023/12/18
logsource:
  category: file_access
  product: windows
tactics:
- Credential Access
relevantTechniques:
- T1003
query: 'DeviceFileEvents

  | where ((FileName contains "\\Appdata\\Local\\Chrome\\User Data\\Default\\Login
  Data" or FileName contains "\\AppData\\Local\\Google\\Chrome\\User Data\\Default\\Network\\Cookies"
  or FileName contains "\\AppData\\Local\\Google\\Chrome\\User Data\\Local State")
  or (FileName endswith "\\cookies.sqlite" or FileName endswith "release\\key3.db"
  or FileName endswith "release\\key4.db" or FileName endswith "release\\logins.json")
  or FileName endswith "\\Appdata\\Local\\Microsoft\\Windows\\WebCache\\WebCacheV01.dat")
  and (not(((InitiatingProcessFolderPath contains ":\\Program Files (x86)\\" or InitiatingProcessFolderPath
  contains ":\\Program Files\\" or InitiatingProcessFolderPath contains ":\\Windows\\system32\\"
  or InitiatingProcessFolderPath contains ":\\Windows\\SysWOW64\\") or InitiatingProcessFolderPath
  =~ "System"))) and (not(((InitiatingProcessFolderPath contains ":\\ProgramData\\Microsoft\\Windows
  Defender\\" and (InitiatingProcessFolderPath endswith "\\MpCopyAccelerator.exe"
  or InitiatingProcessFolderPath endswith "\\MsMpEng.exe")) or (InitiatingProcessFolderPath
  endswith "\\thor64.exe" or InitiatingProcessFolderPath endswith "\\thor.exe"))))'
eventGroupingSettings:
  aggregationKind: SingleAlert
queryFrequency: P1D
queryPeriod: P1D
enabled: true
entityMappings: null
sentinelEntitiesMappings: null
triggerThreshold: 0
suppressionDuration: PT5H
suppressionEnabled: false
triggerOperator: GreaterThan
kind: Scheduled
