name: ADS Zone.Identifier Deleted By Uncommon Application
id: 3109530e-ab47-4cc6-a953-cac5ebcc93ae
author: Nasreddine Bencherchali (Nextron Systems)
date: 2023/09/04
severity: medium
description: Detects the deletion of the "Zone.Identifier" ADS by an uncommon process.
  Attackers can leverage this in order to bypass security restrictions that make use
  of the ADS such as Microsoft Office apps.
status: experimental
modified: 2024/04/26
logsource:
  category: file_delete
  product: windows
tactics:
- Defense Evasion
relevantTechniques:
- T1070
query: 'DeviceFileEvents

  | where FolderPath endswith ":Zone.Identifier" and (not((InitiatingProcessFolderPath
  in~ ("C:\\Program Files\\PowerShell\\7-preview\\pwsh.exe", "C:\\Program Files\\PowerShell\\7\\pwsh.exe",
  "C:\\Windows\\explorer.exe", "C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\powershell.exe",
  "C:\\Windows\\SysWOW64\\explorer.exe", "C:\\Windows\\SysWOW64\\WindowsPowerShell\\v1.0\\powershell.exe"))))
  and (not(((InitiatingProcessFolderPath in~ ("C:\\Program Files (x86)\\Google\\Chrome\\Application\\chrome.exe",
  "C:\\Program Files\\Google\\Chrome\\Application\\chrome.exe")) or (InitiatingProcessFolderPath
  in~ ("C:\\Program Files (x86)\\Mozilla Firefox\\firefox.exe", "C:\\Program Files\\Mozilla
  Firefox\\firefox.exe")))))'
eventGroupingSettings:
  aggregationKind: SingleAlert
queryFrequency: P1D
queryPeriod: P1D
enabled: true
entityMappings: null
sentinelEntitiesMappings: null
triggerThreshold: 0
suppressionDuration: PT5H
suppressionEnabled: false
triggerOperator: GreaterThan
kind: Scheduled
