name: Credential Manager Access By Uncommon Applications
id: 407aecb1-e762-4acf-8c7b-d087bcff3bb6
author: Nasreddine Bencherchali (Nextron Systems)
date: 2022/10/11
severity: medium
description: 'Detects suspicious processes based on name and location that access
  the windows credential manager and vault.

  Which can be a sign of credential stealing. Example case would be usage of mimikatz
  "dpapi::cred" function

  '
status: experimental
modified: 2024/07/29
logsource:
  category: file_access
  product: windows
tactics:
- Credential Access
relevantTechniques:
- T1003
query: 'DeviceFileEvents

  | where (FileName contains "\\AppData\\Local\\Microsoft\\Credentials\\" or FileName
  contains "\\AppData\\Roaming\\Microsoft\\Credentials\\" or FileName contains "\\AppData\\Local\\Microsoft\\Vault\\"
  or FileName contains "\\ProgramData\\Microsoft\\Vault\\") and (not((InitiatingProcessFolderPath
  startswith "C:\\Program Files\\" or InitiatingProcessFolderPath startswith "C:\\Program
  Files (x86)\\" or InitiatingProcessFolderPath startswith "C:\\Windows\\system32\\"
  or InitiatingProcessFolderPath startswith "C:\\Windows\\SysWOW64\\")))'
eventGroupingSettings:
  aggregationKind: SingleAlert
queryFrequency: P1D
queryPeriod: P1D
enabled: true
entityMappings: null
sentinelEntitiesMappings: null
triggerThreshold: 0
suppressionDuration: PT5H
suppressionEnabled: false
triggerOperator: GreaterThan
kind: Scheduled
