name: Disable Privacy Settings Experience in Registry
id: 0372e1f9-0fd2-40f7-be1b-a7b2b848fa7b
author: frack113
date: 2022/10/02
severity: medium
description: Detects registry modifications that disable Privacy Settings Experience
status: test
modified: 2023/08/17
logsource:
  category: registry_set
  product: windows
tactics:
- Defense Evasion
relevantTechniques:
- T1562
query: 'DeviceRegistryEvents

  | where RegistryValueData =~ "DWORD (0x00000000)" and RegistryKey endswith "\\SOFTWARE\\Policies\\Microsoft\\Windows\\OOBE\\DisablePrivacyExperience"'
eventGroupingSettings:
  aggregationKind: SingleAlert
queryFrequency: P1D
queryPeriod: P1D
enabled: true
entityMappings: null
sentinelEntitiesMappings: null
triggerThreshold: 0
suppressionDuration: PT5H
suppressionEnabled: false
triggerOperator: GreaterThan
kind: Scheduled
