name: File With Uncommon Extension Created By An Office Application
id: c7a74c80-ba5a-486e-9974-ab9e682bc5e4
author: Vadim Khrykov (ThreatIntel), Cyb3rEng (Rule), Nasreddine Bencherchali (Nextron
  Systems)
date: 2021/08/23
severity: high
description: Detects the creation of files with an executable or script extension
  by an Office application.
status: test
modified: 2023/06/22
logsource:
  category: file_event
  product: windows
tactics:
- Execution
relevantTechniques:
- T1204
query: 'DeviceFileEvents

  | where ((InitiatingProcessFolderPath endswith "\\excel.exe" or InitiatingProcessFolderPath
  endswith "\\msaccess.exe" or InitiatingProcessFolderPath endswith "\\mspub.exe"
  or InitiatingProcessFolderPath endswith "\\powerpnt.exe" or InitiatingProcessFolderPath
  endswith "\\visio.exe" or InitiatingProcessFolderPath endswith "\\winword.exe")
  and (FolderPath endswith ".bat" or FolderPath endswith ".cmd" or FolderPath endswith
  ".com" or FolderPath endswith ".dll" or FolderPath endswith ".exe" or FolderPath
  endswith ".hta" or FolderPath endswith ".ocx" or FolderPath endswith ".proj" or
  FolderPath endswith ".ps1" or FolderPath endswith ".scf" or FolderPath endswith
  ".scr" or FolderPath endswith ".sys" or FolderPath endswith ".vbe" or FolderPath
  endswith ".vbs" or FolderPath endswith ".wsf" or FolderPath endswith ".wsh")) and
  (not((FolderPath contains "\\AppData\\Local\\assembly\\tmp\\" and FolderPath endswith
  ".dll"))) and (not(((InitiatingProcessFolderPath endswith "\\winword.exe" and FolderPath
  contains "\\AppData\\Local\\Temp\\webexdelta\\" and (FolderPath endswith ".dll"
  or FolderPath endswith ".exe")) or ((FolderPath contains "C:\\Users\\" and FolderPath
  contains "\\AppData\\Local\\Microsoft\\Office\\" and FolderPath contains "\\WebServiceCache\\AllUsers")
  and FolderPath endswith ".com"))))'
eventGroupingSettings:
  aggregationKind: SingleAlert
queryFrequency: P1D
queryPeriod: P1D
enabled: true
entityMappings: null
sentinelEntitiesMappings: null
triggerThreshold: 0
suppressionDuration: PT5H
suppressionEnabled: false
triggerOperator: GreaterThan
kind: Scheduled
