name: HackTool - RedMimicry Winnti Playbook Execution
id: 95022b85-ff2a-49fa-939a-d7b8f56eeb9b
author: Alexander Rausch
date: 2020/06/24
severity: high
description: Detects actions caused by the RedMimicry Winnti playbook a automated
  breach emulations utility
status: test
modified: 2023/03/01
logsource:
  category: process_creation
  product: windows
tactics:
- Defense Evasion
- Execution
relevantTechniques:
- T1059
- T1106
- T1218
query: 'DeviceProcessEvents

  | where (ProcessCommandLine contains "gthread-3.6.dll" or ProcessCommandLine contains
  "\\Windows\\Temp\\tmp.bat" or ProcessCommandLine contains "sigcmm-2.4.dll") and
  (FolderPath endswith "\\rundll32.exe" or FolderPath endswith "\\cmd.exe")'
eventGroupingSettings:
  aggregationKind: SingleAlert
queryFrequency: P1D
queryPeriod: P1D
enabled: true
entityMappings: null
sentinelEntitiesMappings: null
triggerThreshold: 0
suppressionDuration: PT5H
suppressionEnabled: false
triggerOperator: GreaterThan
kind: Scheduled
