name: Legitimate Application Dropped Archive
id: 654fcc6d-840d-4844-9b07-2c3300e54a26
author: frack113, Florian Roth
date: 2022/08/21
severity: high
description: Detects programs on a Windows system that should not write an archive
  to disk
status: test
modified: ''
logsource:
  category: file_event
  product: windows
tactics:
- Defense Evasion
relevantTechniques:
- T1218
query: 'DeviceFileEvents

  | where (InitiatingProcessFolderPath endswith "\\winword.exe" or InitiatingProcessFolderPath
  endswith "\\excel.exe" or InitiatingProcessFolderPath endswith "\\powerpnt.exe"
  or InitiatingProcessFolderPath endswith "\\msaccess.exe" or InitiatingProcessFolderPath
  endswith "\\mspub.exe" or InitiatingProcessFolderPath endswith "\\eqnedt32.exe"
  or InitiatingProcessFolderPath endswith "\\visio.exe" or InitiatingProcessFolderPath
  endswith "\\wordpad.exe" or InitiatingProcessFolderPath endswith "\\wordview.exe"
  or InitiatingProcessFolderPath endswith "\\certutil.exe" or InitiatingProcessFolderPath
  endswith "\\certoc.exe" or InitiatingProcessFolderPath endswith "\\CertReq.exe"
  or InitiatingProcessFolderPath endswith "\\Desktopimgdownldr.exe" or InitiatingProcessFolderPath
  endswith "\\esentutl.exe" or InitiatingProcessFolderPath endswith "\\finger.exe"
  or InitiatingProcessFolderPath endswith "\\notepad.exe" or InitiatingProcessFolderPath
  endswith "\\AcroRd32.exe" or InitiatingProcessFolderPath endswith "\\RdrCEF.exe"
  or InitiatingProcessFolderPath endswith "\\mshta.exe" or InitiatingProcessFolderPath
  endswith "\\hh.exe") and (FolderPath endswith ".zip" or FolderPath endswith ".rar"
  or FolderPath endswith ".7z" or FolderPath endswith ".diagcab" or FolderPath endswith
  ".appx")'
eventGroupingSettings:
  aggregationKind: SingleAlert
queryFrequency: P1D
queryPeriod: P1D
enabled: true
entityMappings: null
sentinelEntitiesMappings: null
triggerThreshold: 0
suppressionDuration: PT5H
suppressionEnabled: false
triggerOperator: GreaterThan
kind: Scheduled
