name: Lsass Full Dump Request Via DumpType Registry Settings
id: 33efc23c-6ea2-4503-8cfe-bdf82ce8f719
author: '@pbssubhash'
date: 2022/12/08
severity: high
description: Detects the setting of the "DumpType" registry value to "2" which stands
  for a "Full Dump". Technique such as LSASS Shtinkering requires this value to be
  "2" in order to dump LSASS.
status: test
modified: 2023/08/17
logsource:
  category: registry_set
  product: windows
tactics:
- Credential Access
relevantTechniques:
- T1003
query: 'DeviceRegistryEvents

  | where RegistryValueData =~ "DWORD (0x00000002)" and (RegistryKey contains "\\SOFTWARE\\Microsoft\\Windows\\Windows
  Error Reporting\\LocalDumps\\DumpType" or RegistryKey contains "\\SOFTWARE\\Microsoft\\Windows\\Windows
  Error Reporting\\LocalDumps\\lsass.exe\\DumpType")'
eventGroupingSettings:
  aggregationKind: SingleAlert
queryFrequency: P1D
queryPeriod: P1D
enabled: true
entityMappings: null
sentinelEntitiesMappings: null
triggerThreshold: 0
suppressionDuration: PT5H
suppressionEnabled: false
triggerOperator: GreaterThan
kind: Scheduled
