name: Microsoft Teams Sensitive File Access By Uncommon Applications
id: 65744385-8541-44a6-8630-ffc824d7d4cc
author: '@SerkinValery'
date: 2024/07/22
severity: medium
description: 'Detects file access attempts to sensitive Microsoft teams files (leveldb,
  cookies) by an uncommon process.

  '
status: experimental
modified: ''
logsource:
  category: file_access
  product: windows
tactics:
- Credential Access
relevantTechniques:
- T1528
query: 'DeviceFileEvents

  | where (FileName contains "\\Microsoft\\Teams\\Cookies" or FileName contains "\\Microsoft\\Teams\\Local
  Storage\\leveldb") and (not(InitiatingProcessFolderPath endswith "\\Microsoft\\Teams\\current\\Teams.exe"))'
eventGroupingSettings:
  aggregationKind: SingleAlert
queryFrequency: P1D
queryPeriod: P1D
enabled: true
entityMappings: null
sentinelEntitiesMappings: null
triggerThreshold: 0
suppressionDuration: PT5H
suppressionEnabled: false
triggerOperator: GreaterThan
kind: Scheduled
