name: Modification of IE Registry Settings
id: d88d0ab2-e696-4d40-a2ed-9790064e66b3
author: frack113
date: 2022/01/22
severity: low
description: Detects modification of the registry settings used for Internet Explorer
  and other Windows components that use these settings. An attacker can abuse this
  registry key to add a domain to the trusted sites Zone or insert javascript for
  persistence
status: test
modified: 2023/08/17
logsource:
  category: registry_set
  product: windows
tactics:
- Defense Evasion
relevantTechniques:
- T1112
query: 'DeviceRegistryEvents

  | where RegistryKey contains "\\Software\\Microsoft\\Windows\\CurrentVersion\\Internet
  Settings" and (not((RegistryKey contains "\\Accepted Documents" or RegistryValueData
  =~ "Binary Data" or RegistryValueData startswith "DWORD" or (RegistryValueData in~
  ("Cookie:", "Visited:", "(Empty)")) or (RegistryKey contains "\\Cache" or RegistryKey
  contains "\\ZoneMap" or RegistryKey contains "\\WpadDecision"))))'
eventGroupingSettings:
  aggregationKind: SingleAlert
queryFrequency: P1D
queryPeriod: P1D
enabled: true
entityMappings: null
sentinelEntitiesMappings: null
triggerThreshold: 0
suppressionDuration: PT5H
suppressionEnabled: false
triggerOperator: GreaterThan
kind: Scheduled
