name: New Application in AppCompat
id: 60936b49-fca0-4f32-993d-7415edcf9a5d
author: Roberto Rodriguez (Cyb3rWard0g), OTR (Open Threat Research)
date: 2020/05/02
severity: informational
description: A General detection for a new application in AppCompat. This indicates
  an application executing for the first time on an endpoint.
status: test
modified: 2023/08/17
logsource:
  category: registry_set
  product: windows
tactics:
- Execution
relevantTechniques:
- T1204
query: 'DeviceRegistryEvents

  | where RegistryKey contains "\\AppCompatFlags\\Compatibility Assistant\\Store"'
eventGroupingSettings:
  aggregationKind: SingleAlert
queryFrequency: P1D
queryPeriod: P1D
enabled: true
entityMappings: null
sentinelEntitiesMappings: null
triggerThreshold: 0
suppressionDuration: PT5H
suppressionEnabled: false
triggerOperator: GreaterThan
kind: Scheduled
