name: New BgInfo.EXE Custom WMI Query Registry Configuration
id: cd277474-5c52-4423-a52b-ac2d7969902f
author: Nasreddine Bencherchali (Nextron Systems)
date: 2023-08-16
severity: medium
description: Detects setting of a new registry value related to BgInfo configuration,
  which can be abused to execute custom WMI query via "BgInfo.exe"
status: test
modified: ''
logsource:
  category: registry_set
  product: windows
tactics:
- Defense-evasion
relevantTechniques:
- T1112
query: 'DeviceRegistryEvents

  | where RegistryValueData startswith "6" and ActionType =~ "RegistryValueSet" and
  RegistryKey contains "\\Software\\Winternals\\BGInfo\\UserFields\\"'
eventGroupingSettings:
  aggregationKind: SingleAlert
queryFrequency: P1D
queryPeriod: P1D
enabled: true
entityMappings: null
sentinelEntitiesMappings: null
triggerThreshold: 0
suppressionDuration: PT5H
suppressionEnabled: false
triggerOperator: GreaterThan
kind: Scheduled
