name: Outlook Security Settings Updated - Registry
id: c3cefdf4-6703-4e1c-bad8-bf422fc5015a
author: frack113
date: 2021/12/28
severity: medium
description: Detects changes to the registry values related to outlook security settings
status: test
modified: 2023/08/17
logsource:
  category: registry_set
  product: windows
tactics:
- Persistence
relevantTechniques:
- T1137
query: 'DeviceRegistryEvents

  | where RegistryKey contains "\\SOFTWARE\\Microsoft\\Office" and RegistryKey contains
  "\\Outlook\\Security"'
eventGroupingSettings:
  aggregationKind: SingleAlert
queryFrequency: P1D
queryPeriod: P1D
enabled: true
entityMappings: null
sentinelEntitiesMappings: null
triggerThreshold: 0
suppressionDuration: PT5H
suppressionEnabled: false
triggerOperator: GreaterThan
kind: Scheduled
