name: Rclone Config File Creation
id: 34986307-b7f4-49be-92f3-e7a4d01ac5db
author: Aaron Greetham (@beardofbinary) - NCC Group
date: 2021/05/26
severity: medium
description: Detects Rclone config files being created
status: test
modified: 2023/05/09
logsource:
  category: file_event
  product: windows
tactics:
- Exfiltration
relevantTechniques:
- T1567
query: 'DeviceFileEvents

  | where FolderPath contains ":\\Users\\" and FolderPath contains "\\.config\\rclone\\"'
eventGroupingSettings:
  aggregationKind: SingleAlert
queryFrequency: P1D
queryPeriod: P1D
enabled: true
entityMappings: null
sentinelEntitiesMappings: null
triggerThreshold: 0
suppressionDuration: PT5H
suppressionEnabled: false
triggerOperator: GreaterThan
kind: Scheduled
