name: RDP File Creation From Suspicious Application
id: fccfb43e-09a7-4bd2-8b37-a5a7df33386d
author: Nasreddine Bencherchali (Nextron Systems)
date: 2023-04-18
severity: high
description: Detects Rclone config file being created
status: test
modified: ''
logsource:
  category: file_event
  product: windows
tactics:
- Defense-evasion
relevantTechniques: []
query: 'DeviceFileEvents

  | where (InitiatingProcessFolderPath endswith "\\brave.exe" or InitiatingProcessFolderPath
  endswith "\\CCleaner Browser\\Application\\CCleanerBrowser.exe" or InitiatingProcessFolderPath
  endswith "\\chromium.exe" or InitiatingProcessFolderPath endswith "\\firefox.exe"
  or InitiatingProcessFolderPath endswith "\\Google\\Chrome\\Application\\chrome.exe"
  or InitiatingProcessFolderPath endswith "\\iexplore.exe" or InitiatingProcessFolderPath
  endswith "\\microsoftedge.exe" or InitiatingProcessFolderPath endswith "\\msedge.exe"
  or InitiatingProcessFolderPath endswith "\\Opera.exe" or InitiatingProcessFolderPath
  endswith "\\Vivaldi.exe" or InitiatingProcessFolderPath endswith "\\Whale.exe" or
  InitiatingProcessFolderPath endswith "\\Outlook.exe" or InitiatingProcessFolderPath
  endswith "\\RuntimeBroker.exe" or InitiatingProcessFolderPath endswith "\\Thunderbird.exe"
  or InitiatingProcessFolderPath endswith "\\Discord.exe" or InitiatingProcessFolderPath
  endswith "\\Keybase.exe" or InitiatingProcessFolderPath endswith "\\msteams.exe"
  or InitiatingProcessFolderPath endswith "\\Slack.exe" or InitiatingProcessFolderPath
  endswith "\\teams.exe") and FolderPath contains ".rdp"'
eventGroupingSettings:
  aggregationKind: SingleAlert
queryFrequency: P1D
queryPeriod: P1D
enabled: true
entityMappings: null
sentinelEntitiesMappings: null
triggerThreshold: 0
suppressionDuration: PT5H
suppressionEnabled: false
triggerOperator: GreaterThan
kind: Scheduled
