name: RDP Sensitive Settings Changed
id: 3f6b7b62-61aa-45db-96bd-9c31b36b653c
author: Samir Bousseaden, David ANDRE, Roberto Rodriguez @Cyb3rWard0g, Nasreddine
  Bencherchali
date: 2022/08/06
severity: high
description: 'Detects tampering of RDP Terminal Service/Server sensitive settings.

  Such as allowing unauthorized users access to a system via the ''fAllowUnsolicited''
  or enabling RDP via ''fDenyTSConnections''...etc

  '
status: test
modified: 2024/02/08
logsource:
  category: registry_set
  product: windows
tactics:
- Defense Evasion
- Persistence
relevantTechniques:
- T1112
query: 'DeviceRegistryEvents

  | where ((RegistryValueData in~ ("DWORD (0x00000001)", "DWORD (0x00000002)", "DWORD
  (0x00000003)", "DWORD (0x00000004)")) and (RegistryKey contains "\\Control\\Terminal
  Server" or RegistryKey contains "\\Windows NT\\Terminal Services") and RegistryKey
  endswith "\\Shadow") or (RegistryValueData =~ "DWORD (0x00000001)" and (RegistryKey
  contains "\\Control\\Terminal Server" or RegistryKey contains "\\Windows NT\\Terminal
  Services") and (RegistryKey endswith "\\DisableRemoteDesktopAntiAlias" or RegistryKey
  endswith "\\DisableSecuritySettings" or RegistryKey endswith "\\fAllowUnsolicited"
  or RegistryKey endswith "\\fAllowUnsolicitedFullControl")) or (RegistryKey contains
  "\\Control\\Terminal Server\\InitialProgram" or RegistryKey contains "\\Control\\Terminal
  Server\\WinStations\\RDP-Tcp\\InitialProgram" or RegistryKey contains "\\services\\TermService\\Parameters\\ServiceDll"
  or RegistryKey contains "\\Windows NT\\Terminal Services\\InitialProgram")'
eventGroupingSettings:
  aggregationKind: SingleAlert
queryFrequency: P1D
queryPeriod: P1D
enabled: true
entityMappings: null
sentinelEntitiesMappings: null
triggerThreshold: 0
suppressionDuration: PT5H
suppressionEnabled: false
triggerOperator: GreaterThan
kind: Scheduled
