name: RDP Sensitive Settings Changed to Zero
id: a2863fbc-d5cb-48d5-83fb-d976d4b1743b
author: Samir Bousseaden, David ANDRE, Roberto Rodriguez @Cyb3rWard0g, Nasreddine
  Bencherchali
date: 2022/09/29
severity: medium
description: 'Detects tampering of RDP Terminal Service/Server sensitive settings.

  Such as allowing unauthorized users access to a system via the ''fAllowUnsolicited''
  or enabling RDP via ''fDenyTSConnections'', etc.

  '
status: test
modified: 2022/11/26
logsource:
  category: registry_set
  product: windows
tactics:
- Defense Evasion
- Persistence
relevantTechniques:
- T1112
query: 'DeviceRegistryEvents

  | where RegistryValueData =~ "DWORD (0x00000000)" and (RegistryKey endswith "\\fDenyTSConnections"
  or RegistryKey endswith "\\fSingleSessionPerUser" or RegistryKey endswith "\\UserAuthentication")'
eventGroupingSettings:
  aggregationKind: SingleAlert
queryFrequency: P1D
queryPeriod: P1D
enabled: true
entityMappings: null
sentinelEntitiesMappings: null
triggerThreshold: 0
suppressionDuration: PT5H
suppressionEnabled: false
triggerOperator: GreaterThan
kind: Scheduled
