name: Run Once Task Configuration in Registry
id: c74d7efc-8826-45d9-b8bb-f04fac9e4eff
author: Avneet Singh @v3t0_, oscd.community
date: 2020-11-15
severity: medium
description: Rule to detect the configuration of Run Once registry key. Configured
  payload can be run by runonce.exe /AlternateShellStartup
status: test
modified: 2024-03-25
logsource:
  category: registry_event
  product: windows
tactics:
- Defense-evasion
relevantTechniques:
- T1112
query: 'DeviceRegistryEvents

  | where (RegistryKey contains "\\Microsoft\\Active Setup\\Installed Components"
  and RegistryKey endswith "\\StubPath") and (not(((RegistryValueData contains "C:\\Program
  Files\\Google\\Chrome\\Application\\" and RegistryValueData contains "\\Installer\\chrmstp.exe\"
  --configure-user-settings --verbose-logging --system-level") or ((RegistryValueData
  contains "C:\\Program Files (x86)\\Microsoft\\Edge\\Application\\" or RegistryValueData
  contains "C:\\Program Files\\Microsoft\\Edge\\Application\\") and RegistryValueData
  endswith "\\Installer\\setup.exe\" --configure-user-settings --verbose-logging --system-level
  --msedge --channel=stable"))))'
eventGroupingSettings:
  aggregationKind: SingleAlert
queryFrequency: P1D
queryPeriod: P1D
enabled: true
entityMappings: null
sentinelEntitiesMappings: null
triggerThreshold: 0
suppressionDuration: PT5H
suppressionEnabled: false
triggerOperator: GreaterThan
kind: Scheduled
