name: Suspicious File Created Via OneNote Application
id: fcc6d700-68d9-4241-9a1a-06874d621b06
author: Nasreddine Bencherchali (Nextron Systems)
date: 2023/02/09
severity: high
description: Detects suspicious files created via the OneNote application. This could
  indicate a potential malicious ".one"/".onepkg" file was executed as seen being
  used in malware activity in the wild
status: test
modified: 2023/02/27
logsource:
  category: file_event
  product: windows
tactics:
- Defense Evasion
relevantTechniques: []
query: 'DeviceFileEvents

  | where (InitiatingProcessFolderPath endswith "\\onenote.exe" or InitiatingProcessFolderPath
  endswith "\\onenotem.exe" or InitiatingProcessFolderPath endswith "\\onenoteim.exe")
  and FolderPath contains "\\AppData\\Local\\Temp\\OneNote\\" and (FolderPath endswith
  ".bat" or FolderPath endswith ".chm" or FolderPath endswith ".cmd" or FolderPath
  endswith ".dll" or FolderPath endswith ".exe" or FolderPath endswith ".hta" or FolderPath
  endswith ".htm" or FolderPath endswith ".html" or FolderPath endswith ".js" or FolderPath
  endswith ".lnk" or FolderPath endswith ".ps1" or FolderPath endswith ".vbe" or FolderPath
  endswith ".vbs" or FolderPath endswith ".wsf")'
eventGroupingSettings:
  aggregationKind: SingleAlert
queryFrequency: P1D
queryPeriod: P1D
enabled: true
entityMappings: null
sentinelEntitiesMappings: null
triggerThreshold: 0
suppressionDuration: PT5H
suppressionEnabled: false
triggerOperator: GreaterThan
kind: Scheduled
