name: Suspicious Electron Application Child Processes
id: f26eb764-fd89-464b-85e2-dc4a8e6e77b8
author: Nasreddine Bencherchali (Nextron Systems)
date: 2022-10-21
severity: medium
description: 'Detects suspicious child processes of electron apps (teams, discord,
  slack, etc.). This could be a potential sign of ".asar" file tampering (See reference
  section for more information) or binary execution proxy through specific CLI arguments
  (see related rule)

  '
status: test
modified: 2024-07-12
logsource:
  category: process_creation
  product: windows
tactics:
- Execution
relevantTechniques: []
query: 'DeviceProcessEvents

  | where (InitiatingProcessFolderPath endswith "\\chrome.exe" or InitiatingProcessFolderPath
  endswith "\\discord.exe" or InitiatingProcessFolderPath endswith "\\GitHubDesktop.exe"
  or InitiatingProcessFolderPath endswith "\\keybase.exe" or InitiatingProcessFolderPath
  endswith "\\msedge.exe" or InitiatingProcessFolderPath endswith "\\msedgewebview2.exe"
  or InitiatingProcessFolderPath endswith "\\msteams.exe" or InitiatingProcessFolderPath
  endswith "\\slack.exe" or InitiatingProcessFolderPath endswith "\\teams.exe") and
  ((FolderPath endswith "\\cmd.exe" or FolderPath endswith "\\cscript.exe" or FolderPath
  endswith "\\mshta.exe" or FolderPath endswith "\\powershell.exe" or FolderPath endswith
  "\\pwsh.exe" or FolderPath endswith "\\regsvr32.exe" or FolderPath endswith "\\whoami.exe"
  or FolderPath endswith "\\wscript.exe") or (FolderPath contains ":\\ProgramData\\"
  or FolderPath contains ":\\Temp\\" or FolderPath contains "\\AppData\\Local\\Temp\\"
  or FolderPath contains "\\Users\\Public\\" or FolderPath contains "\\Windows\\Temp\\"))
  and (not((ProcessCommandLine contains "\\NVSMI\\nvidia-smi.exe" and FolderPath endswith
  "\\cmd.exe" and InitiatingProcessFolderPath endswith "\\Discord.exe")))'
eventGroupingSettings:
  aggregationKind: SingleAlert
queryFrequency: P1D
queryPeriod: P1D
enabled: true
entityMappings: null
sentinelEntitiesMappings: null
triggerThreshold: 0
suppressionDuration: PT5H
suppressionEnabled: false
triggerOperator: GreaterThan
kind: Scheduled
