name: UAC Bypass Using MSConfig Token Modification - File
id: 41bb431f-56d8-4691-bb56-ed34e390906f
author: Christian Burkard (Nextron Systems)
date: 2021/08/30
severity: high
description: Detects the pattern of UAC Bypass using a msconfig GUI hack (UACMe 55)
status: test
modified: 2022/10/09
logsource:
  category: file_event
  product: windows
tactics:
- Defense Evasion
- Privilege Escalation
relevantTechniques:
- T1548
query: 'DeviceFileEvents

  | where FolderPath endswith "\\AppData\\Local\\Temp\\pkgmgr.exe" and FolderPath
  startswith "C:\\Users\\"'
eventGroupingSettings:
  aggregationKind: SingleAlert
queryFrequency: P1D
queryPeriod: P1D
enabled: true
entityMappings: null
sentinelEntitiesMappings: null
triggerThreshold: 0
suppressionDuration: PT5H
suppressionEnabled: false
triggerOperator: GreaterThan
kind: Scheduled
