name: Uncommon  Assistive Technology Applications Execution Via AtBroker.EXE
id: f24bcaea-0cd1-11eb-adc1-0242ac120002
author: Mateusz Wydra, oscd.community
date: 2020/10/12
severity: medium
description: Detects the start of a non built-in assistive technology applications
  via "Atbroker.EXE".
status: test
modified: 2024/03/06
logsource:
  category: process_creation
  product: windows
tactics:
- Defense Evasion
relevantTechniques:
- T1218
query: 'DeviceProcessEvents

  | where (ProcessCommandLine contains "start" and (FolderPath endswith "\\AtBroker.exe"
  or ProcessVersionInfoOriginalFileName =~ "AtBroker.exe")) and (not((ProcessCommandLine
  contains "animations" or ProcessCommandLine contains "audiodescription" or ProcessCommandLine
  contains "caretbrowsing" or ProcessCommandLine contains "caretwidth" or ProcessCommandLine
  contains "colorfiltering" or ProcessCommandLine contains "cursorindicator" or ProcessCommandLine
  contains "cursorscheme" or ProcessCommandLine contains "filterkeys" or ProcessCommandLine
  contains "focusborderheight" or ProcessCommandLine contains "focusborderwidth" or
  ProcessCommandLine contains "highcontrast" or ProcessCommandLine contains "keyboardcues"
  or ProcessCommandLine contains "keyboardpref" or ProcessCommandLine contains "livecaptions"
  or ProcessCommandLine contains "magnifierpane" or ProcessCommandLine contains "messageduration"
  or ProcessCommandLine contains "minimumhitradius" or ProcessCommandLine contains
  "mousekeys" or ProcessCommandLine contains "Narrator" or ProcessCommandLine contains
  "osk" or ProcessCommandLine contains "overlappedcontent" or ProcessCommandLine contains
  "showsounds" or ProcessCommandLine contains "soundsentry" or ProcessCommandLine
  contains "speechreco" or ProcessCommandLine contains "stickykeys" or ProcessCommandLine
  contains "togglekeys" or ProcessCommandLine contains "voiceaccess" or ProcessCommandLine
  contains "windowarranging" or ProcessCommandLine contains "windowtracking" or ProcessCommandLine
  contains "windowtrackingtimeout" or ProcessCommandLine contains "windowtrackingzorder")))
  and (not(ProcessCommandLine contains "Oracle_JavaAccessBridge"))'
eventGroupingSettings:
  aggregationKind: SingleAlert
queryFrequency: P1D
queryPeriod: P1D
enabled: true
entityMappings: null
sentinelEntitiesMappings: null
triggerThreshold: 0
suppressionDuration: PT5H
suppressionEnabled: false
triggerOperator: GreaterThan
kind: Scheduled
