name: Windows Terminal Profile Settings Modification By Uncommon Process
id: 9b64de98-9db3-4033-bd7a-f51430105f00
author: frack113, Nasreddine Bencherchali (Nextron Systems)
date: 2023/07/22
severity: medium
description: Detects the creation or modification of the Windows Terminal Profile
  settings file "settings.json" by an uncommon process.
status: test
modified: ''
logsource:
  category: file_event
  product: windows
tactics:
- Persistence
relevantTechniques:
- T1547
query: 'DeviceFileEvents

  | where (InitiatingProcessFolderPath endswith "\\cmd.exe" or InitiatingProcessFolderPath
  endswith "\\cscript.exe" or InitiatingProcessFolderPath endswith "\\mshta.exe" or
  InitiatingProcessFolderPath endswith "\\powershell.exe" or InitiatingProcessFolderPath
  endswith "\\pwsh.exe" or InitiatingProcessFolderPath endswith "\\wscript.exe") and
  FolderPath endswith "\\AppData\\Local\\Packages\\Microsoft.WindowsTerminal_8wekyb3d8bbwe\\LocalState\\settings.json"'
eventGroupingSettings:
  aggregationKind: SingleAlert
queryFrequency: P1D
queryPeriod: P1D
enabled: true
entityMappings: null
sentinelEntitiesMappings: null
triggerThreshold: 0
suppressionDuration: PT5H
suppressionEnabled: false
triggerOperator: GreaterThan
kind: Scheduled
