name: Winget Admin Settings Modification
id: 6db5eaf9-88f7-4ed9-af7d-9ef2ad12f236
author: Nasreddine Bencherchali (Nextron Systems)
date: 2023-04-17
severity: low
description: Detects changes to the AppInstaller (winget) admin settings. Such as
  enabling local manifest installations or disabling installer hash checks
status: test
modified: 2023-08-17
logsource:
  category: registry_set
  product: windows
tactics:
- Defense-evasion
- Persistence
relevantTechniques: []
query: 'DeviceRegistryEvents

  | where InitiatingProcessFolderPath endswith "\\winget.exe" and RegistryKey endswith
  "\\LocalState\\admin_settings" and RegistryKey startswith "\\REGISTRY\\A\\"'
eventGroupingSettings:
  aggregationKind: SingleAlert
queryFrequency: P1D
queryPeriod: P1D
enabled: true
entityMappings: null
sentinelEntitiesMappings: null
triggerThreshold: 0
suppressionDuration: PT5H
suppressionEnabled: false
triggerOperator: GreaterThan
kind: Scheduled
